export const data = {
    tableRows: [
      {
        id: 1,
        firstName: "Jon",
        lastName: "Snow",
        age: 35,
        fullName: "Jon Snow",
        isEditable : false,
      },
      {
        id: 2,
        firstName: "Cersei",
        lastName: "Lannister",
        age: 42,
        fullName: "Cersei Lannister",
        isEditable : false,
      },
      {
        id: 3,
        firstName: "Jaime",
        lastName: "Lannister",
        age: 45,
        fullName: "Jaime Lannister",
        isEditable : false,
      },
      {
        id: 4,
        firstName: "Arya",
        lastName: "Stark",
        age: 16,
        fullName: "Arya Stark",
        isEditable : false,
      },
      {
        id: 5,
        firstName: "Daenerys",
        lastName: "Targaryen",
        age: 35,
        fullName: "Daenerys Targaryen",
        isEditable : false,
      },
      {
        id: 6,
        firstName: "",
        lastName: "Melisandre",
        age: 150,
        fullName: "Melisandre",
        isEditable : false,
      },
      {
        id: 7,
        firstName: "Ferrara",
        lastName: "Clifford",
        age: 44,
        fullName: "Ferrara Clifford",
        isEditable : false,
      },
      {
        id: 8,
        firstName: "Rossini",
        lastName: "Frances",
        age: 36,
        fullName: "Rossini Frances",
        isEditable : false,
      },
      {
        id: 9,
        firstName: "Harvey",
        lastName: "Roxie",
        age: 65,
        fullName: "Harvey Roxie",
        isEditable : false,
      },
      {
        id: 10,
        firstName: "Dharani",
        lastName: "Chinnagala Bhaskarbabu",
        age: 24,
        fullName: "Dharani CB",
        isEditable : false,
      },
    ],
      tableCols : [
        {
          id: 1,
          name: "id",
          headName : "ID",
          isEditable : false,
        },
        {
          id: 2,
          name: "firstName",
          headName : "First Name",
          isEditable : true,
        },
        {
          id: 3,
          name: "lastName",
          headName : "Last Name",
          isEditable : true,
        },
        {
          id: 4,
          name: "age",
          headName : "Age",
          isEditable : true,
        },
        {
          id: 5,
          name: "fullName",
          headName : "Full Name",
          isEditable : false,
        },
      ],

  };